version: "3"

services:
  api:
    build:
      context: .
    restart: unless-stopped
    pid: host
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - cron_config:/cron

volumes:
  cron_config: