// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Joseph Kuhnsman",
            "email": "admin@ftkuhnsman.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/operator": {
            "get": {
                "description": "Responds with the Operator attributes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get the Streamr Operator details.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Operator"
                            }
                        }
                    }
                }
            }
        },
        "/operator/deployedstake/": {
            "get": {
                "description": "Responds with the Operator stake deployed in all sponsorships.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get the Streamr Operator total deployed stake.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DeployedStakeResponse"
                            }
                        }
                    }
                }
            }
        },
        "/operator/reducestaketo/{sponsorship}/{amount}": {
            "get": {
                "description": "Responds with the transaction hash.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Change Streamr Operator stake on a given sponsor.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sponsorship address",
                        "name": "sponsorship",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "amount in wei",
                        "name": "amount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TransactionResponse"
                            }
                        }
                    }
                }
            }
        },
        "/operator/sponsorshipsandearnings": {
            "get": {
                "description": "Responds with the list of sponsorships and uncollected earnings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get the sponsorships and earnings.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Operator"
                            }
                        }
                    }
                }
            }
        },
        "/operator/stake/{sponsorship}/{amount}": {
            "get": {
                "description": "Responds with the transaction hash.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Increase Streamr Operator stake on a given sponsor.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sponsorship address",
                        "name": "sponsorship",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "amount in wei",
                        "name": "amount",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TransactionResponse"
                            }
                        }
                    }
                }
            }
        },
        "/operator/stakedinto/{address}": {
            "get": {
                "description": "Responds with the Operator stake deployed in sponsorship.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get the Streamr Operator staked balance in sponsorship.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "get deployed stake by sponsorship",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StakedIntoResponse"
                            }
                        }
                    }
                }
            }
        },
        "/operator/valuewithoutearnings": {
            "get": {
                "description": "Responds with the Operator attributes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get the Streamr Operator details.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Operator"
                            }
                        }
                    }
                }
            }
        },
        "/operator/withdrawearnings": {
            "get": {
                "description": "Responds with the Operator attributes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Get the Streamr Operator details.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TransactionResponse"
                            }
                        }
                    }
                }
            }
        },
        "/operator/withdrawearningsandcompound": {
            "get": {
                "description": "Withdraws earnings from all sponsorships and restake to compound.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operator"
                ],
                "summary": "Withdraw earnings from sponsorship and restake.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.TransactionResponse"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "abi.ABI": {
            "type": "object",
            "properties": {
                "constructor": {
                    "$ref": "#/definitions/github_com_ethereum_go-ethereum_accounts_abi.Method"
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/abi.Error"
                    }
                },
                "events": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/abi.Event"
                    }
                },
                "fallback": {
                    "description": "Additional \"special\" functions introduced in solidity v0.6.0.\nIt's separated from the original default fallback. Each contract\ncan only define one fallback and receive function.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_ethereum_go-ethereum_accounts_abi.Method"
                        }
                    ]
                },
                "methods": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_ethereum_go-ethereum_accounts_abi.Method"
                    }
                },
                "receive": {
                    "$ref": "#/definitions/github_com_ethereum_go-ethereum_accounts_abi.Method"
                }
            }
        },
        "abi.Argument": {
            "type": "object",
            "properties": {
                "indexed": {
                    "description": "indexed is only used by events",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_ethereum_go-ethereum_accounts_abi.Type"
                }
            }
        },
        "abi.Error": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID returns the canonical representation of the error's signature used by the\nabi definition to identify event names and types.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/abi.Argument"
                    }
                },
                "name": {
                    "type": "string"
                },
                "sig": {
                    "description": "Sig contains the string signature according to the ABI spec.\ne.g. error foo(uint32 a, int b) = \"foo(uint32,int256)\"\nPlease note that \"int\" is substitute for its canonical representation \"int256\"",
                    "type": "string"
                }
            }
        },
        "abi.Event": {
            "type": "object",
            "properties": {
                "anonymous": {
                    "type": "boolean"
                },
                "id": {
                    "description": "ID returns the canonical representation of the event's signature used by the\nabi definition to identify event names and types.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/abi.Argument"
                    }
                },
                "name": {
                    "description": "Name is the event name used for internal representation. It's derived from\nthe raw name and a suffix will be added in the case of event overloading.\n\ne.g.\nThese are two events that have the same name:\n* foo(int,int)\n* foo(uint,uint)\nThe event name of the first one will be resolved as foo while the second one\nwill be resolved as foo0.",
                    "type": "string"
                },
                "rawName": {
                    "description": "RawName is the raw event name parsed from ABI.",
                    "type": "string"
                },
                "sig": {
                    "description": "Sig contains the string signature according to the ABI spec.\ne.g.\t event foo(uint32 a, int b) = \"foo(uint32,int256)\"\nPlease note that \"int\" is substitute for its canonical representation \"int256\"",
                    "type": "string"
                }
            }
        },
        "abi.FunctionType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "Constructor",
                "Fallback",
                "Receive",
                "Function"
            ]
        },
        "big.Int": {
            "type": "object"
        },
        "github_com_ethereum_go-ethereum_accounts_abi.Method": {
            "type": "object",
            "properties": {
                "constant": {
                    "description": "Legacy indicators generated by compiler before v0.6.0",
                    "type": "boolean"
                },
                "id": {
                    "description": "ID returns the canonical representation of the method's signature used by the\nabi definition to identify method names and types.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/abi.Argument"
                    }
                },
                "name": {
                    "description": "Name is the method name used for internal representation. It's derived from\nthe raw name and a suffix will be added in the case of a function overload.\n\ne.g.\nThese are two functions that have the same name:\n* foo(int,int)\n* foo(uint,uint)\nThe method name of the first one will be resolved as foo while the second one\nwill be resolved as foo0.",
                    "type": "string"
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/abi.Argument"
                    }
                },
                "payable": {
                    "type": "boolean"
                },
                "rawName": {
                    "description": "RawName is the raw method name parsed from ABI",
                    "type": "string"
                },
                "sig": {
                    "description": "Sig returns the methods string signature according to the ABI spec.\ne.g.\t\tfunction foo(uint32 a, int b) = \"foo(uint32,int256)\"\nPlease note that \"int\" is substitute for its canonical representation \"int256\"",
                    "type": "string"
                },
                "stateMutability": {
                    "description": "StateMutability indicates the mutability state of method,\nthe default value is nonpayable. It can be empty if the abi\nis generated by legacy compiler.",
                    "type": "string"
                },
                "type": {
                    "description": "Type indicates whether the method is a\nspecial fallback introduced in solidity v0.6.0",
                    "allOf": [
                        {
                            "$ref": "#/definitions/abi.FunctionType"
                        }
                    ]
                }
            }
        },
        "github_com_ethereum_go-ethereum_accounts_abi.Type": {
            "type": "object",
            "properties": {
                "elem": {
                    "$ref": "#/definitions/github_com_ethereum_go-ethereum_accounts_abi.Type"
                },
                "size": {
                    "type": "integer"
                },
                "t": {
                    "description": "Our own type checking",
                    "type": "integer"
                },
                "tupleElems": {
                    "description": "Type information of all tuple fields",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ethereum_go-ethereum_accounts_abi.Type"
                    }
                },
                "tupleRawName": {
                    "description": "Tuple relative fields",
                    "type": "string"
                },
                "tupleRawNames": {
                    "description": "Raw field name of all tuple fields",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tupleType": {
                    "description": "Underlying struct of the tuple"
                }
            }
        },
        "models.DeployedStakeResponse": {
            "type": "object",
            "properties": {
                "deployedBySponsorship": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/big.Int"
                    }
                },
                "totalDeployed": {
                    "$ref": "#/definitions/big.Int"
                }
            }
        },
        "models.Operator": {
            "type": "object",
            "properties": {
                "contractAbi": {
                    "$ref": "#/definitions/abi.ABI"
                },
                "contractAddr": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "ownerAddr": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.StakedIntoResponse": {
            "type": "object",
            "properties": {
                "stakedInto": {
                    "$ref": "#/definitions/big.Int"
                }
            }
        },
        "models.TransactionResponse": {
            "type": "object",
            "properties": {
                "txHash": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Streamr Operator Service",
	Description:      "A Streamr Operator management service API in Go using Gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
